### ISSUE TITLE
Week 1st-comment

### ISSUE THREAD

**Issue by parvizi** [3DCloud/Server#1]
1-	Please explain key things to accomplish and criteria for success
2-	Please make an issue tab and a project by clicking on ‘Projects’ close to ‘Wiki’ and make a board where you can monitor your tasks easily. Also, add issues to monitor your tasks.
3-	Who are your team members?

**Comment by nicoco007** [comment]
Sorry, I could have sworn I had replied to this already. Regarding your points

1. I've added them to the Project Overview page in the wiki.
2. I'm actually using ZenHub for task/issue tracking, which is built on top of GitHub Issues and adds a few extra features like epics. I've sent the invitation link in Teams.
3. I'm actually working on this alone; do you still want me to add a Team Members section with only my name?
